### ISSUE TITLE
Negotiating DTLS version between 1.2 and 1.3

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#104]
The specification is supporting both DTLS 1.2 and DTLS 1.3. Do we need a discussion how an client or server can negotiate which DTLS version to use and are there a downgrade risk here. And can that be handled in other ways that having the ULP mandate particular versions?

**Comment by emanjon** [comment]
I assume the DTLS version negotiation is handled by the DTLS handshake and that nothing more is needed, or? If both sides support DTLS 1.3, they will never negotiate anything lower.

We should definitly explain how the negotiation of the DTLS version is done.

**Comment by gloinul** [comment]
So the reason i was raising this issue are the interoperability issues, and the relationship to usage of DTLS/SCTP for various ULPs.

First of all we have no discussion of the fact that in the generic case one endpoint can support version X and the other Y and that can lead to failure. 

Secondly, there exist potential for downgrade attacks if one version is weaker than the other and supporting both on server side. 

Third, the possible need for an ULP to be actually dictate what applies for DTLS/SCTP usage for that particular ULP. This I assume will be the norm for the 3GPP protocols where 3GPP Specs will define which DTLS version(s) is to be used and supported.

**Comment by emanjon** [comment]
Yes, looks like we should have some discussion about this. We should maybe also say more about fallback to RFC 6083 and the interoperability and downgrade attacks there.

> First of all we have no discussion of the fact that in the generic case one endpoint can support version X and the other Y and that can lead to failure.

Yes, should acknoledge that there might be failure. One option could be to mandate one or more versions. For 3GPP use cases, 3GPP would like to follow the 3GPP TLS profile, which takes care of interoperability between releases. so I don't thing it is needed for 3GPP.

> Secondly, there exist potential for downgrade attacks if one version is weaker than the other and supporting both on server side.

For DTLS there are no downgrade attacks. DTLS protects against that. There are likely downgrade attacks when falling back to RFC 6083

We should say that the same DTLS version SHALL be used when setting up a new DTLS connection in the same SCTP association. I think that is missing.

**Comment by emanjon** [comment]
Fallback to RFC 6083 and downgrade attacks are alrady described. Closing this issue.
