### ISSUE TITLE
Do we need better recommendations for Receiver Buffer sizing?

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#107]
Daria raised a potential issues: 

"Retransmission negatively impacts on performance. So, it would be good to recommend to set receiver buffer side at least to 2*(2048 + 13(or more because header of message with CID is longer than usual header of DTLS record) + 2^14 )  for such traffic." 
This is for traffic that does not support I-DATA but send multiple messages at the same time but in continuous TSN ranges to fit the whole message. 

So I think we need to consider if it should be clarified how to interact with the SCTP receiver buffer.

**Comment by emanjon** [comment]
I don't know where the numbers above come from (except 2^14), but note that DTLS 1.2 has quite varying overhead based on the cipher suite.

https://datatracker.ietf.org/doc/html/draft-mattsson-uta-tls-overhead

**Comment by gloinul** [comment]
So to start with these numbers. I think the 2048 is actually to ensure a complete SCTP packet fits, where 2048 would be plenty for common MTU. The 13 is DTLS overhead and as stated it might be more than 13. 2^14 is clearly the maximum DTLS record. The two times I would say is to avoid the stalling of SCTP as each DTLS record is being processed by DTLS and then the clear text copied/transferred into ULP's memory space.

However, to me it looks like going into detail here might actually result in errors or faulty assumptions. So I think we want to keep the advice general. We already have this text:

   The security operations and reassembly process requires that the
   protected user message, i.e., with DTLS record overhead, is buffered
   in the receiver. This buffer space will thus put a limit on the
   largest size of plain text user message that can be transferred
   securely. However, by mandating the use of the partial delivery of
   user messages from SCTP and assuming that no two messages received
   on the same stream are interleaved (as it is the case when using
   the API defined in {{RFC6458}}) the required buffering prior to
   DTLS processing can be limited to a single DTLS record per used
   incoming stream. This enables the DTLS/SCTP implementation to
   provide the Upper Layer Protocol (ULP) with each DTLS record's
   content when it has been decrypted and its integrity been verified
   enabling partial user message delivery to the ULP. Implementations
   can trade-off buffer memory requirements in the DTLS layer with
   transport overhead by using smaller DTLS records.

I would think the clarification here is to avoid retransmissions or flow control stalls due to lack of receiver space it would be good to have more than a single DTLS record with overhead per stream. So I think a minor clarification about the potential impact here of having to little space.
