### ISSUE TITLE
Mandate non-zero CID values in DTLS

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#108]
In Section 4.1 of -03 there is this sentence:

"Thus, it is RECOMMENDED to not use the zero length CID values and instead use a single common length for the CID values."

Daria commented that to avoid the implementation handling of zero-length case why not mandate that non-zero MUST be used?

I think that is a valid idea, especially as non-zero is not suitable and only result in extra issues in this usage.

**Comment by emanjon** [comment]
Seems like a good idea to me.
