### ISSUE TITLE
Don't refer to partial message API

### ISSUE THREAD

**Issue by tuexen** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#11]
SCTP stacks can handle large received messages. There is no requirement to use the SocketAPI, although we make sure things can be implemented using it...

**Comment by gloinul** [comment]
So we can probably update the text to be more generic in the requirement on messages sizes. Possibly we could move the whole discussion about the interaction between the different layer's buffering requirement into an appendix.

**Comment by teiclap** [comment]
Reference to Socket API has been removed from the text in commitment 8d09ca0...
