### ISSUE TITLE
Key update

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#123]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-1.1.2-4.2 says:

> Enable DTLS key-change without requiring draining all inflight user message from SCTP.

I think that you are talking about key updates.  This is a feature of DTLS 1.3, not DTLS 1.2, so it might be worth pointing that out.

**Comment by gloinul** [comment]
No, this is actually not referring to the DTLS 1.3 specific key-update, instead it is referring to the general aspect of key-exchange. RFC 6083 if one is using renegotiation in DTLS 1.2 or DTLS 1.3 Key-update one may in both cases end up in a situation where DTLS handling of old keys results in that the old key is discard prior to all old records having been received and processed. 

Will address this with an update to #157.
