### ISSUE TITLE
"semi-permanent" might be better as "long-lived"

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#125]
Permanent or not, there is no semi-permanent.  Half of infinity is still infinity.  And in this business, there is no permanent.

**Comment by teiclap** [comment]
Semi-permanent is a definition from the telecom world, it's strictly related to the circuit switched network.
A semi-permanent connection is something that once set-up will never be removed.
The use of "semi-permanent" can be explained in the document but it's different from long-lived.
