### ISSUE TITLE
Overview material is lacking

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#127]
When I got to Section 3.3, I still had no idea how DTLS and SCTP interacted with each other.  So I had no basis for understanding what the text was attempting to say.  Maybe consider adding some material ahead of Section 3 that describes how the two protocols interact at a high level.

**Comment by martinthomson** [comment]
The same applies to connection ID usage.  This is mentioned as being mandatory: "As this solution requires multiple connection IDs," but there is no basis for understanding that claim.

**Comment by gloinul** [comment]
Yes, we clearly should add a section describing how DTLS/SCTP operates as a layer between the ULP and the SCTP stack, and how it uses parallel connections and identifies the incoming DTLS records and messages based on the connection ID.
