### ISSUE TITLE
DTLS record size limit

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#130]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-3.3-4 says:

> Implementations can trade-off buffer memory requirements in the DTLS layer with transport overhead by using smaller DTLS records. 

This is not true unless you use the [record size limit extension](https://datatracker.ietf.org/doc/html/rfc8449) for DTLS (RFC 8449).  The sender determines the record size, but the receiver is the one that has to commit the buffers.  Consider recommending use of RFC 8449 here.

**Comment by gloinul** [comment]
There is a proposal for how to deal with this issue in #132.
