### ISSUE TITLE
Connection IDs at the DTLS layer

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#134]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-4.1-11 says:

> The DTLS Connection ID MUST be negotiated ([[RFC9146](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#RFC9146)] or Section 9 of [[RFC9147](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#RFC9147)]). If DTLS 1.3 is used, the length field in the record layer MUST be included in all records.

This will result in connection IDs appearing in chunks all over the place as DTLS records are fragmented and sent in different chunks.  Consequently, this will rarely be useful for routing purposes, meaning that it is just wasteful.

Isn't there a better mechanism within SCTP for labeling chunks with this sort of routing information?  If there isn't why not build one?

**Comment by martinthomson** [comment]
OK, there were a few more clues scattered through Section 4 that hinted at why this is the case.  This is a surprising design, so please take time to consider #127.

**Comment by gloinul** [comment]
So, with PR #166 I think the question of why we use them not to route, but to determine crypto context for the decryption operation should be clear enough.
