### ISSUE TITLE
DTLS anti-replay might fail

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#136]
...spectacularly.

#135 outlines an issue with sequence numbers, but the problem extends to DTLS replay protection.  Having more records that are effectively in flight means that you need an anti-replay window that is large enough to cover all those messages.  Where DTLS messages might be retransmitted (over multiple PTOs even), that window might need to be very large.  Many DTLS implementations are unable to tune the size of this window (NSS has a fixed 1024-message window), so that will just lead to records failing to be accepted.  

This manifests as a decryption failure, which effectively creates a fourth [failure mode](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-4.1-8.1): where the anti-replay falsely marks a record as being a replay - not because it is, but because the sequence number is outside of the window it is actively tracking.

Given how this sort of error results in connections being torn down, that is not likely to produce very good results.

FWIW, I don't find the analysis [here](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-4.1-12) compelling.  I think that #130 and #132 already cover the record size assumption; and I don't see a 64kbit anti-replay window as credible.

**Comment by gloinul** [comment]
Yes, that is why we have a put in a requirement to turn that off, see https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#name-replay-protection. If that is not possible then that is an issue that can reduce the amount of stacks available to this usage. 

Will consider the editorial if anti-replay should be listed as a failure mode to with a pointer to where we mandate it as off. 

I will expand the sequence number motivation a bit in #135 to explain why it should work and there is a difference between the sequence number aspect and the key-lifetime.
