### ISSUE TITLE
Forced caching

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#138]
This design essentially forces receivers to cache DTLS records for each active DTLS connection establishment.  Because decryption failure is so disastrous, if there is any race between a TLS Finished and records for that connection, a receiver might be stuck caching more than they might ordinarily be prepared to handle.  Does the SCTP flow control manage this properly?

**Comment by teiclap** [comment]
DTLS flow control mechanism is based on SACK and prevents caching more than what can be possibly handled.

**Comment by gloinul** [comment]
So in the bottom we have the SCTP stack and its receiver window which can contain data from various user message in transit at least when I-DATA is used. The protected user messages are either whole (if smaller) or partially read by DTLS/SCTP. As soon as a DTLS/SCTP has a complete DTLS record it can request decryption of it, and then take that part of the ULP data and provide it to the ULP. Thus, the amount of cached data in the DTLS/SCTP layer is one DTLS record per stream. So this caching of data is necessary for the function of DTLS/SCTP. If an receiving ULP does not read the unprotected data and DTLS/SCTP actually would run out of memory to hold that data that would result in a pushback when the receiver buffer fill up as DTLS/SCTP stops consuming data. So from the perspective the flow control aspects do work. 

When it comes to DTLS connection closing that is why we have defined a procedure. So the peer will not send a close until it knows that the data have been completely ACKed by the receiver, thus all that data can be read by the receiver application. Thus, ensuring that a receiver will have read up all data protected by the DTLS connection before it can receive Ready_to_Close. So before actually closing the DTLS Connection, the implementation can ensure that all cached records are processed, and then close the connection. 

So, yes there are a certain amount of minimal buffering required, but it is quite limited to maintain functionality. And the DTLS/SCTP layer will result in back pressure to the sender side if the ULP do not read the data. I hope that answers your concern.

**Comment by gloinul** [comment]
Closing this as answered as PR #169 should additional clarify this issue.
