### ISSUE TITLE
Negotiating the SCTP-AUTH hash

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#140]
It seems like you might benefit from setting the SCTP-AUTH hash to the hash function used by the negotiated TLS PRF.  This would allow for stronger authentication that matches the negotiated TLS parameters.

**Comment by gloinul** [comment]
So currently SCTP-AUTH only support SHA-1 and SHA-256, where we require the later. Which to my understanding matches what is the default PRF in DTLS 1.2. I fail to full understand what the algorithms are used by the HKDF in TLS 1.3. 

But the implication for this specification would be to basically say, prefer to use an SCTP-AUTH hash algorithm that matches hash algorithm used by the TLS PRF and HKDF respectively?

**Comment by emanjon** [comment]
> prefer to use an SCTP-AUTH hash algorithm that matches hash algorithm used by the TLS PRF and HKDF respectively?

I think Martin suggests to have a one-to-one mapping between the hash function in the negotiated TLS cipher suite and the SCTP-AUTH hash algorithm. That is a good idea in theory but I think it has a lot of problems. 
- To my understanding SCTP-AUTH is used before the TLS handshake. Can the algorithms even be changed in the middle of an association?
- TLS_AES_256_GCM_SHA384 could not be used as SHA-384 is not defined for SCTP AUTH
- There are discussions to standardize new SCTP AUTH algorithms with 128 bit tags, these would then not be usable by DTLS/SCTP.

As long as we forbid SHA-1 to be used, there is currently no practical benefits with securely negotiating the hash function. 

We could say "prefer to use an SCTP-AUTH hash algorithm that matches the TLS cipher suite hash algorithm" as you suggested @gloinul
