### ISSUE TITLE
Parallel DTLS connections from different versions

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#142]
Can you negotiate DTLS 1.2 and DTLS 1.3 concurrently?  Why would you want to allow that?

**Comment by gloinul** [comment]
So I think you mean if it would be okay if one switch DTLS Version when negotiating a second DTLS connection for the purpose of rekeying. I think the short answer is MUST NOT do it. I would motivate it with that even if it would be technically possibly it creates rarely executed code paths and difficult to compare changes in security parameters etc. Thus, it becomes a more likely place for security vulnerabilities and thus it becomes best to forbid it. 

Thus, some text should be added to make this clear.
