### ISSUE TITLE
DTLS glare

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#144]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-4.7-4 blew my tiny mind:

> As either endpoint can initiate a DTLS handshake on either side at the same time, either endpoint may receive a DTLS ClientHello when it has sent its own ClientHello. 

This assumes that both endpoints are authenticating, otherwise you can't swap TLS roles.  This needs a clearer statement about this assumption.

The glare resolution method seems fine with the two-connection limit in place, mostly.  If an endpoint is currently a server and it needs to create a new connection for any reason (it is running out of AEAD usage, say) then it can send a ClientHello.  The peer can effectively deny this request by sending its own ClientHello in response, invoking the glare logic.  That seems like a perfectly reasonable response.  But if you allow for that, then it might be better spelled with a SCTP-layer message to request the former client initiate a new handshake; the new DTLS/SCTP control message seems perfect.

FWIW, I'm not even sure if role swapping is entirely safe.  There might be features that are directional in TLS, which you won't be able to rely on.

**Comment by gloinul** [comment]
So mutual authentication is mandatory: https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#name-authentication-and-policy-d. 

Will have to think more about this second aspect. What is clear is that either endpoint must be able to initiate a rekeying. The DTLS/SCTP control messages is a new thing, and you are right that it can be used to initiate such a request for rekeying.

**Comment by gloinul** [comment]
To clarify what DTLS roles endpoints to support, possibly note that you maintain your client role.

**Comment by emanjon** [comment]
- We should check if we need to mention that mutual authenticated DTLS (with server and client certificate) in more places. That this was not clear to Martin might indicate that it could be mentioned more. Let's check.

> What is clear is that either endpoint must be able to initiate a rekeying.
I don't have any strong opinions if this should be done with ClientHello or on the SCTP level. Let's discuss that

>FWIW, I'm not even sure if role swapping is entirely safe. There might be features that are directional in TLS, which you won't be able to rely on.
From a DTLS perspective this is a completely new connection so I don't see any security problems. Directional features in (or outside) TLS that lives between connections would be affected. I see two such features:
1. Resumption. This does not work if you swap roles so a full handshake has to be done. I don't this is a problem for DTLS/SCTP. We should maybe mention this if it is not mentioned.
2. Certificates. To be able to swap roles both parties need certificates possible to use in both client and server roles. This is outside of TLS. DTLS/SCTP could go inte some details but I am not sure it should. We should probably mention this consideration high level. In practice the solution could be to have 1 cert or 2 different cers (for SBA I think 3GPP allows both). In practice a single cert should have both id-kp-serverAuth  and id-kp-clientAuth. To follow RFC6125bis it should likely have a SAN of type DNSname.

**Comment by emanjon** [comment]
Make PR with implementation, resumption, and certificate considerations.

**Comment by gloinul** [comment]
Resolved this issues.
