### ISSUE TITLE
Ready_To_Close doesn't identify which connection

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#145]
I'm concerned that the reliability of the Ready_To_Close message relative to DTLS-layer close messages could create some issues.

Let's say that you decide to send both of these at the same time, but only one arrives.  The peer discards state based on receiving either.  If RTC arrives after, especially if a new connection attempt has been started in the meantime, then it ends up closing the wrong connection.

I haven't mapped all of this out, but the level of detail in the spec doesn't make me confident that this has been thought through fully.

**Comment by gloinul** [comment]
So, with the limitation of having only two DTLS connections in an association at anytime, at the time one sends the Ready_To_Close there should only be one that is known to be the older. And if you are doing things with both you are entering shutdown. 

But, I think to avoid any issues adding a field to this message is trivial to carry the DTLS connection ID that would ensure that any missing case in me going through them will not break the protocol.

**Comment by gloinul** [comment]
Proposal for how to resolve in #170
