### ISSUE TITLE
DTLS connection establishment during shutdown

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#146]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-4.10-4.2 says: 

> In case a DTLS connection handshake is ongoing this needs to be aborted conclusively at this step to ensure that the necessary DTLS message exchange happens prior to draining any outstanding data in the SCTP association from this endpoint.

Because connections are make-before break (except initially), I don't see why you need to hold the shutdown for the new connection establishment.  The shutdown should be able to proceed with the old keys.

Or are you concerned that the old keys might wear out?  In that case, you should decouple shutdown from the DTLS connection state entirely.  An extended shutdown might need to involve multiple new DTLS connections (especially if you decide to use CCM_8, which has keys wear out very quickly in this context).

Consider only the special case of the first DTLS connection, where you should not have any in-flight user data.  For that, you might just tear the connection down without any extended shutdown process.

**Comment by martinthomson** [comment]
In other words, I'm not convinced that there is any special need for a shutdown process that is specific to this adaptation layer.  Provided that the ULP has adequate provisions for shutdown, this adaptation layer should continue to function and provide service until the ULP decides to quit.  At that point, you can just close the association fully.

**Comment by martinthomson** [comment]
No, I'm suggesting that you operate the two layers independently.  The DTLS connections you make (or not) can continue to be made as needed during shutdown.  If one of those connections is half-way setup, then just abandon it with no further ceremony, it won't be offended.

**Comment by gloinul** [comment]
I think the issue I see is that if you continue and ever start using a new DTLS connection when having entered shutdown progress you have to ensure that any ULP data sent with it has been delivered and handled before doing SCTP level shutdown. Thus, I think abandoning before completing is just fine, but if you ever sent any ULP data you need to close it down. However, as it is on the responsibility of the data sender to verify this I will attempt to clarify that up to this point one can just abandon the DTLS handshake.

**Comment by gloinul** [comment]
Resolved by #177

**Comment by gloinul** [comment]
Resolved by #177
