### ISSUE TITLE
Define how the SCTP-AUTH keys are derived

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#148]
There is an exporter defined in the IANA considerations, but no specification for this.

I'll note that RFC 4895 is pretty poorly specified as well.  It might be worth re-iterating the entire process.

**Comment by gloinul** [comment]
Yes, I believe this is something we can write a detailed description on.

**Comment by emanjon** [comment]
There is the following text

`When a subsequent DTLS connection is setup, a new a 64-byte shared secret is derived using the TLS-Exporter. The shared secret identifiers form a sequence. If the previous shared secret used Shared Key Identifier n, the new one MUST use Shared Key Identifier n+1, unless n = 65535, in which case the new Shared Key Identifier is 1.
`
This text is basically the same as RFC 6083. It should be clearer defined which label is used and that no context is used.

The 64-byte shared secret is quite specific for HMAC-SHA-1 and HMAC-SHA-256 that are the only algorithms currently defined by RFC 4895. HMAC allows any key length to be used but it is recommended to use the same key size as the block size of the hash function. 64-bytes align with the block size for SHA-1 and  SHA-256 but not e.g. SHA-512.

If someone registers AES-CMAC a 64 byte key would not work. We might want to say something different than RFC 6083. TSVWG might work on an RFC4895bis in the near future.

**Comment by emanjon** [comment]
Updated text should use the RFC 4895 term "endpoint pair shared keys".

- Just read up on SCTP-AUTH. From the "endpoint pair shared key" SCTP-AUTH computes the "association shared key" by concatenating the two key vectors (RANDOM parameter, the CHUNKS parameter, and the HMAC-ALGO parameter) from the SCTP handshake. The resulting "association shared key" will therefore be larger than 64 bytes.

- If the key is larger than the block size (which it is in this case as SHA-256 has a block size of 64 bytes), HMAC-SHA-256 will start by deriving a new key K' = SHA-256(K).

**Comment by emanjon** [comment]
Reading more in RFC 4895.

The SCTP handshake negotiate two lists of HMAC algorithms that can be used. These are included in the association key but the used HMAC algorithm is not included in the key derivation.

My understanding of RFC 4895 is that "The receiver of an HMAC-ALGO parameter SHOULD use the first
   listed algorithm it supports." but thre does not seem to be forbidded to change algorithm during the association. Using the same key for several algorithms is generally considered bad design.
   
draft-westerlund-tsvwg-dtls-over-sctp-bis should probably require that each peer use a  single SCTP-AUTH algorithm during the SCTP association.

**Comment by emanjon** [comment]
The ASCII string "EXPORTER-DTLS-OVER-SCTP-EXT" with no terminating NUL.
