### ISSUE TITLE
IANA Section needs to be completed for Adaptation Layer Indication

### ISSUE THREAD

**Issue by tuexen** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#15]
Use an adaptation layer indication

**Comment by gloinul** [comment]
Yes, this has been accepted among the authors, and the removal of the DTLS-supported option has been done in PR #18.

Doesn't the IANA section for the Adaptation layer need a bit more text?

**Comment by tuexen** [comment]
Normally I provide the table entry to be added, but I don't know how to do tables in Markdown, according to the markdown spec in https://spec.commonmark.org/0.29/.

**Comment by gloinul** [comment]
So if you want to make a table, then it is more a question of how kramdown handles this. 

Depending on what you want to accomplish. I noticed that HTTP/3 spec has a table in this section:

https://www.ietf.org/archive/id/draft-ietf-quic-http-34.html#name-http-framing-layer

The markdown source for that table is the below.

| Frame          | Control Stream | Request Stream | Push Stream | Section                  |
| -------------- | -------------- | -------------- | ----------- | ------------------------ |
| DATA           | No             | Yes            | Yes         | {{frame-data}}           |
| HEADERS        | No             | Yes            | Yes         | {{frame-headers}}        |
| CANCEL_PUSH    | Yes            | No             | No          | {{frame-cancel-push}}    |
| SETTINGS       | Yes (1)        | No             | No          | {{frame-settings}}       |
| PUSH_PROMISE   | No             | Yes            | No          | {{frame-push-promise}}   |
| GOAWAY         | Yes            | No             | No          | {{frame-goaway}}         |
| MAX_PUSH_ID    | Yes            | No             | No          | {{frame-max-push-id}}    |
| Reserved       | Yes            | Yes            | Yes         | {{frame-reserved}}       |
{: #stream-frame-mapping title="HTTP/3 Frames and Stream Type Overview"}

**Comment by teiclap** [comment]
A new file containing the markdown format "Adaptation_layer_indication.md" has been added for proposal to IANA.

**Comment by gloinul** [comment]
Okay, this needs further work to create a complete IANA section for the Adaptation Layer Indication. Proposal is a start but needs more work.
