### ISSUE TITLE
Resumption performance

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#151]
[This](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-9.5-1) is just false:

> In DTLS/SCTP, there are no significant performance benefits with resumption and an implementation can chose to never issue any tickets.

There is definitely a performance advantage.  You avoid one signature that needs to be generated and validated otherwise.  And certificates don't need to be sent (validation of those can still be done, which is what I believe all browsers do on resumption).  Together, that's pretty significant.

The advice about a single ticket is good though: you only need enough to create the next connection.  Multiple tickets only help if you are making lots of connections and here you have just two.

Resumption is mutually agreed, so if either endpoint wants another copy of their peer's certificate (maybe to get an updated OCSP staple or a new certificate - if the connection is truly long-lived) they can just refuse to offer or accept a ticket.

**Comment by gloinul** [comment]
So from the expected use cases I think the benefit is limited, but you are strictly right that this is resource consumption save. But, if you rekey approximately once an hour, the cost of that rekeying is fairly insignificant, but we should write incorrect things. We will address the text to be factual correct, and if we want to give any recommendation we will motivate it better.

**Comment by emanjon** [comment]
Let's write that resumption has performance benefits for the Web but that these are not really important when setting up the parallel connections in draft-ietf-tsvwg-dtls-over-sctp-bis. The intention was not intended to imply that resumption has no advantages in general.

A more important aspect based on this comment is that I think the text in draft-ietf-tsvwg-dtls-over-sctp-bis seems to assume that resumption is only used for the  parallel connections. Resuption could also be used for the initial DTLS connection. E.g., if the association is shut down for some reson and has to be restarted. Here resumption could have performance benefits for draft-ietf-tsvwg-dtls-over-sctp-bis

**Comment by emanjon** [comment]
I still think the old text was technically correct for parallel connections. Parallel connection are setup relatively infrequently, the nodes will have a single connection, and latency is not important when setting up a parallel connections. I have a hard time see any significant benefits. However I don't think this sentence need to be in the document at all.

I removed the sentence and replaced it with a sentence describing that "Resumption can have significant latency benefits for quickly restarting a broken DTLS/SCTP association."
