### ISSUE TITLE
How do you limit new connections

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#153]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-9.1-11 says:

> Allowing new connections can enable denial-of-service attacks. The endpoints SHOULD limit the frequency of new connections.

How?

**Comment by gloinul** [comment]
So a solution for this is to refuse to close the old one, thus it would be a protocol violation to open up yet another one. That way if one have a minimal life time that results in an acceptable frequency of new connections. I think we are talking here about holding of closing when someone rekeys every few seconds or more frequently.
