### ISSUE TITLE
Mandatory mutual authentication

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#154]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-9.1-12 says, in a rather offhand manner:

> This together with mandatory mutual authentication (on the DTLS layer) and a requirement to not accept new identities 

This is a protocol requirement that should be in the main body of the document, not hidden in [Section 9.4](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-9.4).

**Comment by gloinul** [comment]
Yes, lets find a better place to make this statement.

**Comment by emanjon** [comment]
Agree

**Comment by gloinul** [comment]
As this was editorial will now close this issue.
