### ISSUE TITLE
Authenticating fallback to RFC 6083

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#156]
This is hard, because RFC 6803 never defined any means of validating itself, but I think that you want to define a fallback signal if you end up using the fallback.  This could be implemented using a TLS extension, with the initiating peer indicating that it chose to fall back in the extension.

If there is a downgrade, the responding peer would recognize this extension and abort.  The TLS handshake would then authenticate the inclusion of the extension, making it hard to remove without also breaking TLS authentication.

See also [RFC 7507](https://www.rfc-editor.org/rfc/rfc7507.html), where the SCSV idea is not entirely a bad idea if you also enable weak TLS configurations at the same time.  You could maybe even reuse the SCSV and get better downgrade protection, but that might be unwise as that document is headed for the Historic bin.

**Comment by gloinul** [comment]
First for clarity it is RFC 6083 that defines the previous version of DTLS/SCTP.

Thanks for the idea, this actually looks practically doable which is hard when you are lacking the hooks in the earlier versions. Will discuss with @emanjon about this.

**Comment by emanjon** [comment]
This seems like an excellent idea. Defining a new TLS extension seems like an easy and clean approach. A suitable solution is probably that the extention does not contain any data and that that presence of the extentions mean support of draft-ietf-tsvwg-dtls-over-sctp-bis. Reusing SCSV seems messy. Regarding DTLS versions, it might make sense to just forbid DTLS 1.2 now that DTLS 1.3 is published and supported by several libraries.

**Comment by emanjon** [comment]
@gloinul below is a explanation of how the downgrade protection in TLS 1.3 works

https://blog.gypsyengineer.com/en/security/how-does-tls-1-3-protect-against-downgrade-attacks.html

DTLS 1.3 work the same

```
  random:  Same as for TLS 1.3, except that the downgrade sentinels
      described in Section 4.1.3 of [TLS13] when TLS 1.2 and TLS 1.1 and
      below are negotiated apply to DTLS 1.2 and DTLS 1.0, respectively.
```

**Comment by emanjon** [comment]
I think the next step is to define the fallback extention. We could define that the intiator using RFC 6083 but supporting draft-ietf-tsvwg-dtls-over-sctp-bis use the extension but it is likely simpler that a initiator supporting draft-ietf-tsvwg-dtls-over-sctp-bis always use the extension. The responder abort if RFC 6083 is used, the responder supports draft-ietf-tsvwg-dtls-over-sctp-bis, and the draft-ietf-tsvwg-dtls-over-sctp-bis extension was present.

**Comment by emanjon** [comment]
I made a PR. This is theoretically nice, but is it worth it practically? This requires 3GPP changing the DTLS implementation. I think I will change the PR so that the extension is only send in RFC6083. My understanding is that 3GPP will just forbid fallback. It would then be bad to force more updates to DTLS libraries.
