### ISSUE TITLE
Align terminology with RFC 9260

### ISSUE THREAD

**Issue by emanjon** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#189]
As an example, RFC 9260 use "INIT ACK" while draft-ietf-tsvwg-dtls-over-sctp-bis use "INIT-ACK"

**Comment by emanjon** [comment]
We should check terminology alignment with RFC 8446 and RFC 4895 as well
- I removed some "-" to align with RFC 4895 but there might be more
- RFC 8446 use ClientHello and KeyUpdate when it talks about the exact name of the message but use Client Hello and key update in other parts.

**Comment by teiclap** [comment]
ClientHello is a name and Client Hello is a noun. I will check for such cases

**Comment by teiclap** [comment]
Also I noted that rfc4895 is not aligned with rfc9260 when using INIT-ACK, COOKIE-ECHO etc.

**Comment by gloinul** [comment]
Lets follow RFC 9260 usage as that is the latest spec and current main spec.

**Comment by emanjon** [comment]
Let's check for alignment with RFC 4895 as well. The term "key-id" is used in one place.

**Comment by teiclap** [comment]
key-id --> Key Identifier
done

**Comment by teiclap** [comment]
There's no SCTP-AUTH in 4895, I replace with SCTP AUTH instead that is locally defined.

**Comment by emanjon** [comment]
RFC 9260 talks about SCTP-AUTH .....

`The SCTP Authentication extension SCTP-AUTH [RFC4895]`

**Comment by gloinul** [comment]
> RFC 9260 talks about SCTP-AUTH .....
> 
> `The SCTP Authentication extension SCTP-AUTH [RFC4895]`

I think actually using SCTP-AUTH would be clearer and I think that is fine if RFC 9260 is using it. Should we revert this change?

**Comment by teiclap** [comment]
OK, even though rfc4895 uses SCTP AUTH. 
RFC9260 has higher prio
