### ISSUE TITLE
Usage of SHA-1 in RFC 6083

### ISSUE THREAD

**Issue by tuexen** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#19]
Why is
```
For an RFC 6083 client it is likely that the preferred HMAC-ALGO indicates SHA-1.
```
true? RFC 6083 does not make a statement...

**Comment by gloinul** [comment]
So that statement is based on that SHA-1 is mandatory to implement in 4895 and thus will be included in the algorithm list.

**Comment by tuexen** [comment]
You are correct, that SHA-1 is the only mandatory to implement algorithm, but SHA-256 is also defined. FreeBSD supports both and prefers SHA-256. So when using only FreeBSD machines with RFC 6083, SHA-256 will be used. Linux only implements SHA-1. So if a FreeBSD machine talks to a Linux machine, SHA-1 will be used. There is no statement in RFC 6083 or RFC 4895 that SHA-1 is preferred. The point is: RFC 6083 make no statement and leaves the choice to the SCTP stack.

**Comment by gloinul** [comment]
Understand then lets change this sentence.
