### ISSUE TITLE
Rekeying in DTLS 1.2

### ISSUE THREAD

**Issue by emanjon** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#22]
Renegotiation seems to be disables in a lot of libraries.

https://security.stackexchange.com/questions/24554/should-i-use-ssl-tls-renegotiation/230327#230327

Might be ok as long as RFC 5746 is used,

https://tools.ietf.org/html/rfc5746

but there are still attacks and weaknesses remaining. Not sure how severe the attacks are. But that the feature seems to be disables by default is quite bad. Such corners of the code base is not reviewed much and might contain other bugs and implementation weaknesses....

**Comment by gloinul** [comment]
I think this issue has been handled. 
@emanjon can this issue be closed?
