### ISSUE TITLE
Rekying in DTLS 1.3

### ISSUE THREAD

**Issue by emanjon** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#23]
DTLS 1.3 removed renegotiation and replaces it with symmetric Post-Handshake KeyUpdate.

KeyUpdate provides less security properties than rerunning Diffie-Hellman. This might be ok, but the properties are below what government requirements stipulate for IPsec.

KeyUpdate in DTLS 1.3 does not update the exporter_master_secret. Any update of keys for SCTP-AUTH needs to be done by adding some information to the exporter label.....

**Comment by gloinul** [comment]
@emanjon can this issue be closed?

**Comment by tuexen** [comment]
So what do we do with the keys used by SCTP AUTH, which are based on data from an exporter?

**Comment by gloinul** [comment]
Is this last issue resolved by #43?
