### ISSUE TITLE
Limitation for key material lifetime

### ISSUE THREAD

**Issue by emanjon** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#24]
DTLS 1.2 (from RFC 5246):
  "An upper limit of 24 hours is suggested for
   session ID lifetimes, since an attacker who obtains a master_secret
   may be able to impersonate the compromised party until the
   corresponding session ID is retired."

DTLS 1.3 (from RFC 8446):
  "It is RECOMMENDED that
   implementations place limits on the total lifetime of such keying
   material; these limits should take into account the lifetime of the
   peer's certificate, the likelihood of intervening revocation, and the
   time since the peer's online CertificateVerify signature."

64-bit sequence numers should not be a problem as they require 2^32 records every second for 136 years to overflow. They also reset after KeyUpdate or renegotiation. 

I assume DTLS/SCTP need to override the DTLS 1.2 lifetime of 24 hours.

**Comment by emanjon** [comment]
How long lived would the DTLS/SCTP connections be? days, weeks, months, years?

**Comment by emanjon** [comment]
Likely months or years.

- We need to state explicitly we are not following the DTLS 1.2 suggestion. Can be motivated by the fact that DTLS 1.3 removes it.
- We need to discuss and maybe give recommendations for how often to require authentication, rekeying, and ECDHE, and any lifetime restrictions on key material apply.

In DTLS 1.2,
Renegotiation gives authentication, rekeying, and ECDHE

In DTLS 1.3,
Post-Handshake KeyUpdate at any time gives rekeying
Post-Handshake authenticated  can be done at any time
ECDHE cannot be done inside the conenction and require resumption, which might cause disruptions.

**Comment by emanjon** [comment]
3GPP protocols are semipermanent and assumes a standing association between nodes.

**Comment by emanjon** [comment]
Might be possible to extend TLS 1.3 with a PSF Post-Handshake rekeying mechanism in the future.

**Comment by tuexen** [comment]
> I assume DTLS/SCTP need to override the DTLS 1.2 lifetime of 24 hours.

Isn't it a statement about the lifetime of the session ID when used for session resumption and not a statement about the lifetime of a TLS connection?

**Comment by emanjon** [comment]
"An upper limit of 24 hours is suggested for
session ID lifetimes, since an attacker who obtains a master_secret
may be able to impersonate the compromised party until the
corresponding session ID is retired."

The text is stated in the resumption section, but I don't think the sentence itself is about resumption. In TLS 1.2 the session ID is created in the full handshake and reused in all resumption. So the session ID lifetime could span several connections. I don't think it matters if you do resumption from a security perspective (but I would have to reread TLS 1.2 resumption).

Might be that I am interpreting the sentence wrong, but the session ID lifetimes in DTLS/SCTP would be months or ever years.

**Comment by tuexen** [comment]
So you are basically saying that in particular no TLS connection can live longer that 24 hours?

**Comment by emanjon** [comment]
I think RFC 5216 "suggsts" that. But it is not a normative SHOULD or MUST.

**Comment by tuexen** [comment]
> I think RFC 5216 "suggsts" that. But it is not a normative SHOULD or MUST.

Sure. But it is the basic message... Wasn't aware of that limitation. Thanks for the clarification.

**Comment by gloinul** [comment]
I would think we can close this issue now, if @emanjon you agree, please close it.

**Comment by tuexen** [comment]
> I would think we can close this issue now, if @emanjon you agree, please close it.

How do we update the key material used by SCTP-AUTH in case of DTLS 1.3? I think the PR doesn't describe this.

**Comment by gloinul** [comment]
You don't change the key, you will have to terminate the session if you run out usages of the key for signing. If your application layer can't handle that, then you will have to use DTLS 1.2 for now until a future solution is defined.

**Comment by tuexen** [comment]
Can we make that clear in the text. Basically, if you are using long living SCTP associations, use DTLS 1.2 for now.

**Comment by gloinul** [comment]
Yes, I think that is a sentence or two to clarify that if you need this property then use DTLS 1.2.
