### ISSUE TITLE
Support for STARTTLS

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#35]
So part of the discussion in #27 brought up the case of STARTTLS. I think that needs more consideration as due to even RFC 6083 requirement to have SCTP-AUTH, one can't move from a plain SCTP association to one with DTLS. Instead one actually need to create an association with the intent to use DTLS. So are there any point in attempting to support STARTTLS like for services that use TLS/TCP where it works.

**Comment by tuexen** [comment]
I only know about [RFC 3788](https://tools.ietf.org/html/rfc3788), which requires setting up the SCTP association appropriately, then exchanges the START-TLS and START-TLS-ACK message in the clear and then do TLS. [RFC 6083](https://tools.ietf.org/html/rfc6083) did not exist at that time.

The reason [RFC 3788](https://tools.ietf.org/html/rfc3788) was written is that there were some SIGTRAN specifications already published and they only specified the unsecured protocol. We requested separate port numbers for the protocols over TLS, but IANA declined that. So we had to do the START-TLS dance.

To be honest, in my limited testing I have done for a German mobile operator, I have never seen SIGTRAN over TLS... So I don't have a problem with not supporting START-TLS, we just need to be clear about it.

**Comment by gloinul** [comment]
I think the way forward here is to explicitly note that STARTTLS will not work with this specification.

**Comment by teiclap** [comment]
The note that STARTTLS will not work with this specification has been added.

**Comment by emanjon** [comment]
The way forward and the added note looks good.

**Comment by gloinul** [comment]
The note has been reformulated in the PR due to that it was contextual problematic. We may want to further improve the style of it in the future.
