### ISSUE TITLE
Reaction to plain text prior or during DTLS connection

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#37]
So currently any plain text prior or during a DTLS connection is considered a protocol violation. The reaction to this protocol violation is that it is allowed to do a SCTP association termination (ABORT). This issue is to track two aspect of this, while a related issue is #35 that impacts if plain text occur. But assuming that it can't we should clarify two things.

1. Is MAY the right level or should this be RECOMMENDED or MUST?
2. Should there be a particular error for this being sent back to peer?

**Comment by teiclap** [comment]
The cases where a protocol violation are detected SHOULD be answered with ABORT. 
Text has been updated.
