### ISSUE TITLE
RFC 6083 Fallback Issues

### ISSUE THREAD

**Issue by tuexen** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#54]
* Why Fallback when the correct adaptation layer indication has been received, but the HMAC or CHUNKS parameter is not as expected. Shouldn't we handle this as a protocol violation? An old implementation will not send the adaptation layer indication...
* Should we describe what to do if the adaptation layer indication is received, but DTLS version 1.0 is indicated?

**Comment by emanjon** [comment]
Maybe we should have have a reference to RFC 8996. According to RFC 8996 (that updates RFC 6083) DTLS 1.0 is always a fatal error. Maybe we should have some more text.

"DTLS 1.0 are formally deprecated and prohibited to negotiate and use [RFC8996]."

**Comment by tuexen** [comment]
> Maybe we should have have a reference to RFC 8996. According to RFC 8996 (that updates RFC 6083) DTLS 1.0 is always a fatal error. Maybe we should have some more text.
> 
> "DTLS 1.0 are formally deprecated and prohibited to negotiate and use [RFC8996]."

We already has similar text in `Version of DTLS`. I added the reference.

I also tweaked the text such that we only consider the missing of the adaptation layer indication as a possibility for a fallback.

But why are we restricting this to the client side? A new client can talk to an old server (using DTLS 1.2). Why not also allow an old client talking to a new server?
