### ISSUE TITLE
Supplementary Note on Fragment reassembly

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#82]
From Li Yan:

It is better to add more description in section 4.1 in the current draft.
The description about how to reassemble the fragemented user message in the DTLS layer is not clear enough, and may cause confusion for readers.It is recommended to add further description about it.
For example：
On the receiving side, after getting the user_message’ from SCTP,  DTLS makes use of the length field in the DTLS record header to decrypt the content of the first DTLS record to get m0, then m1......
The length field in DTLS record header is very import for decryption of each DTLS record.According to the length field, the receiving side knows the end of decryption of one DTLS record and the start of the next DTLS record.
Detemining which DTLS record is the last one needs to use the overall length of the user_message’ from SCTP to minus the lenght of each DTLS record.
After the last DTLS record is decrypted, the user_message is reassembled: user_message = m0 | m1 | m2......

**Comment by emanjon** [comment]
Seems good to add some more information on how different length fields are used in Fragment reassembly. Something as suggested above is likely helpful for the reader.

**Comment by emanjon** [comment]
> On the receiving side DTLS is used to decrypt the individual records. 

This gives the wrong impression. Should also state that DTLS implentations can take any number of records. DTLS might be fed each record individually, the whole user_message’, or anything in between.

**Comment by emanjon** [comment]
DTLS 1.3 states "The final record in a datagram can omit the length field."
We should probably say something about this as well

**Comment by gloinul** [comment]
Daria Ivanova also noted the need for better reassembly description.
