### ISSUE TITLE
2^64-1 bytes maximum user message size

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#84]
With the changes there might not in fact exist an clear limitation to user messages. Daria Ivanova asked if there was a reason for this limitation. 

So there are no actual limitation of rekeying operations with the parallel DTLS connection solution. Thus there are no hard limit on SCTP association length. 

The only reason I see for maintaining a 2^64-1 user message size restriction is to make it clear that you can assume that  64-bit pointers and offset and length fields in handling the data will be sufficient. 2^64 is also a very large number that are extremely unlikely to be consumed. At 1 Tbps it will take almost 4,7 years to transfer 2^64 bytes. And that is for a single user message in a single stream. So this utilizing SCTP like like some type of byte stream. 

I think one alternative is to make it clear that there are no hard limit, but that implementations are not required to support user messages larger than 2^64-1 bytes.

**Comment by emanjon** [comment]
>I think one alternative is to make it clear that there are no hard limit, but that implementations are not required to support >user messages larger than 2^64-1 bytes.

That seems like a good alternative to me

**Comment by teiclap** [comment]
Agree.
