### ISSUE TITLE
Comparision with DTLS handshake fragmentation

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#85]
In Section 4.1:

"The fragmentation works similar as the DTLS fragmentation of handshake messages." 

Daria Ivanova noted that this comparison is not accurate. It should be rewritten to actually describe the used mechanism. This is a companion issue to #82 which is the reassembly description part needing improved.

**Comment by emanjon** [comment]
Yes, lets remove this comparison and rewrite it to actually describe the used mechanism.
