### ISSUE TITLE
DTLS/SCTP is an adaptation layer

### ISSUE THREAD

**Issue by gloinul** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#86]
Daria Ivanova noted that there is a potential risk for a race condition between incomming DTLS handshake messages and the DTLS server in the implementations. 

So this is clearly an implementation issue. From a protocol standpoint the SCTP server has been informed about the DTLS/SCTP adaptation layer usage and agreed to it. Thus, that implementation must be ready for DTLS handshake packets part of received user messages, even if the server instance has not yet brought the DTLS server instance up and is ready with all context. 

So the question is if there is any need to note this protocol vs implementation detail in the draft?

**Comment by teiclap** [comment]
The draft must ensure that an implementation is possible but not how to solve race conditions, on the other hand in the specific the race condition may be due to that implementation.
I wouldn't write something like "avoid race conditions" in the draft.

**Comment by gloinul** [comment]
I agree we should not write "avoid race conditions." But one could potentially write something like this. 

When the SCTP Association handshake has concluded with successful negotiation of DTLS/SCTP adaptation layer it is assumed that any DTLS message may be sent by either peer. Implementations that does not have a DTLS endpoint immediately ready on SCTP handshake completion will have to ensure correct caching of the messages until the endpoint is ready.

**Comment by teiclap** [comment]
I agree with the proposed text
